spring:
  profiles:
    active: local
  # DB 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 서버 실행 시 table create -> 종료 시 drop
      ddl-auto: create
    properties:
      hibernate:
        # query 를 system.out 으로 출력
        show_sql: true
        # sql 을 한 줄에 출력이 아니라 보기 편하게 변경
        format_sql: true
        # 실행 되는 query 에 jpql 주석이 달린다.
        use_sql_comments: true

# org.hibernate.sql 을 log 로 출력
logging:
  level:
    org.hibernate.sql: debug
